# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inline_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inlinegalleryimage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='inlinegalleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
