# Generated by Django 4.2.16 on 2024-11-13 13:32

import django.db.models.deletion
import filer_addons.filer_gui.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("filer", "0015_alter_file_owner_alter_file_polymorphic_ctype_and_more"),
        ("inline_download", "0004_auto_20230501_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inlinedownload",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="inlinedownloadentry",
            name="file",
            field=filer_addons.filer_gui.fields.FilerFileField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_download",
                to="filer.file",
                verbose_name="Download",
            ),
        ),
    ]
