# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 09:56
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentnav', '0002_auto_20181011_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnav',
            name='cms_page',
            field=cms.models.fields.PageField(default=None, help_text='Show submenu of this page', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
    ]
