# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-24 11:39
from __future__ import unicode_literals

import cms.models.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contentnav", "0002_auto_20181011_1006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentnav",
            name="cms_page",
            field=cms.models.fields.PageField(
                blank=True,
                default=None,
                help_text="Show submenu of this page",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.Page",
            ),
        ),
    ]
