# Generated by Django 2.2.20 on 2021-08-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundcloud',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='soundcloud_soundcloud', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='Title')),
                ('published', models.BooleanField(default=True, verbose_name='Published?')),
                ('published_from_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Published from')),
                ('published_until_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Published until')),
                ('in_menu', models.BooleanField(default=False, verbose_name='In Menu?')),
                ('layout', models.CharField(blank=True, default='', max_length=64, verbose_name='Layout')),
                ('size', models.CharField(blank=True, default='', max_length=64, verbose_name='Size')),
                ('background', models.CharField(blank=True, default='', max_length=64, verbose_name='Background')),
                ('custom', models.CharField(blank=True, default='', max_length=128, verbose_name='Custom')),
                ('anchor', models.SlugField(blank=True, default='', verbose_name='Anchor')),
                ('soundcloud_url', models.URLField()),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('autoplay', models.BooleanField(default=False)),
                ('show_comments', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
