# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 08:46
from __future__ import unicode_literals

import ckeditor.fields
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0016_auto_20160608_1535"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextImage",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="textimage_textimage",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="Title"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Published?"),
                ),
                (
                    "published_from_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Published from",
                    ),
                ),
                (
                    "published_until_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Published until",
                    ),
                ),
                (
                    "in_menu",
                    models.BooleanField(default=False, verbose_name="In Menu?"),
                ),
                (
                    "layout",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Layout"
                    ),
                ),
                (
                    "background",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Background"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Color"
                    ),
                ),
                (
                    "anchor",
                    models.SlugField(blank=True, default="", verbose_name="Anchor"),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=255)),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                (
                    "body",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Text"),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="textimage_textimage_image",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
