from .settings import *


DJANGOCMS_BASEPLUGINS_MODE = 'full'

IMAGEPLUGIN_DESIGN_FIELDS = [['layout', 'background', 'color', ], ]
SECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
HTMLBLOCKPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
PERSONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
PERSONSECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
TEASERSECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
GALLERYPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
COLUMNPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
TEXTIMAGEPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
TWEETEMBEDPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS