# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-04 06:07
from __future__ import unicode_literals

import ckeditor.fields
import django.db.models.deletion
import filer.fields.image
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('textimage', '0003_auto_20161108_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimage',
            name='background',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='textimage',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='textimage',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='textimage',
            name='image',
            field=filer.fields.image.FilerImageField(null=True,
                                                     on_delete=django.db.models.deletion.SET_NULL,
                                                     related_name='textimage_textimage_image',
                                                     to='filer.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='textimage',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
