# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-04 06:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170403_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='background',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='person',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_person_image', to='filer.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='personsection',
            name='background',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='personsection',
            name='color',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='personsection',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
