# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('person', '0007_auto_20171128_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255,
                                   verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='person',
            name='function',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Function'),
        ),
    ]
