# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0008_auto_20180822_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="fax",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Fax"
            ),
        ),
    ]
