# Generated by Django 2.2.20 on 2021-04-13 09:02

import django.db.models.deletion
import filer_addons.filer_gui.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0009_person_fax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=filer_addons.filer_gui.fields.FilerImageField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_person_image",
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Image",
            ),
        ),
    ]
