# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_video_show_related"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="mute",
            field=models.BooleanField(default=False, verbose_name="mute"),
        ),
    ]
