# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_mute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='infos',
            field=models.BooleanField(default=True, help_text='not for youtube', verbose_name='show infos'),
        ),
    ]
