# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20190921_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='show_related',
            field=models.BooleanField(default=False, help_text='youtube only', verbose_name='show related'),
        ),
    ]
