# Generated by Django 3.2.25 on 2024-11-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0011_auto_20230501_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="oembed_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
