# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 12:54
from __future__ import unicode_literals

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True,
                                                       related_name='contact_contact',
                                                       serialize=False, to='cms.CMSPlugin')),
                ('title',
                 models.CharField(blank=True, default='', max_length=256, verbose_name='Title')),
                ('published', models.BooleanField(default=True, verbose_name='Published?')),
                ('published_from_date', models.DateTimeField(blank=True, default=None, null=True,
                                                             verbose_name='Published from')),
                ('published_until_date', models.DateTimeField(blank=True, default=None, null=True,
                                                              verbose_name='Published until')),
                ('in_menu', models.BooleanField(default=False, verbose_name='In Menu?')),
                ('layout',
                 models.CharField(blank=True, default='', max_length=64, verbose_name='Layout')),
                ('background', models.CharField(blank=True, default='', max_length=64,
                                                verbose_name='Background')),
                ('color',
                 models.CharField(blank=True, default='', max_length=64, verbose_name='Color')),
                ('anchor', models.SlugField(blank=True, default='', verbose_name='Anchor')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('email',
                 models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone',
                 models.CharField(blank=True, default='', max_length=64, verbose_name='Phone')),
                (
                'fax', models.CharField(blank=True, default='', max_length=64, verbose_name='Fax')),
                (
                'body', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Text')),
                ('address',
                 models.CharField(blank=True, default='', max_length=512, verbose_name='Address')),
                ('geocoding_address', models.CharField(blank=True, default='', max_length=64,
                                                       verbose_name='Address for the map')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
