# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_auto_20181024_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Address"),
        ),
    ]
