from .settings import *


DJANGOCMS_BASEPLUGINS_MODE = 'full'

IMAGEPLUGIN_DESIGN_FIELDS = [['layout', 'background', 'color', ], ]
SECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
HTMLBLOCKPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
SECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
SECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
SECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS
SECTIONPLUGIN_DESIGN_FIELDS = IMAGEPLUGIN_DESIGN_FIELDS