# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20171128_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
