# Generated by Django 2.2.20 on 2021-04-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_form_designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefaultvalue',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_values', to='cms_form_designer.FormDesigner'),
        ),
    ]
