# Generated by Django 2.2.20 on 2021-06-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_form_designer', '0002_auto_20210413_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdesigner',
            name='custom',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Custom'),
        ),
        migrations.AddField(
            model_name='formdesigner',
            name='size',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='formdesigner',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='form_designer.Form'),
        ),
    ]
